language: java

notifications:
  email: false

branches:
  only:
  - develop
  - master

deploy:
  provider: heroku
  api_key: "13a3c238-7049-4575-b0cd-34225f86e5fe"
app: projet-team-simond

before_script: cd ./vetapp