language: java

notifications:
  email: false

branches:
  only:
  - develop
  - master

deploy:
  provider: heroku
  api_key: 
    secure: "6fc420b5-9e41-499a-93b1-7d6daf550c17"
  app: projet-team-simond

before_script: cd ./vetapp