language: java

notifications:
  email: false

branches:
  only:
  - develop
  - master

deploy:
  - provider: heroku
    api_key: 
      secure: "2ae3d328-3a72-4e8f-aedb-5bb5739d5bcc"
    app: projet-team-simond
    on:
      branch:
        develop
    skip_cleanup: true

  - provider: heroku
    api_key: 
      secure: "2ae3d328-3a72-4e8f-aedb-5bb5739d5bcc"
    app: projet-team-simond
    on:
      branch:
        master
    skip_cleanup: true

before_script:
  - cd ./vetapp